###Добавить один фильм
POST http://localhost:8190/movie-api/addMovie
Content-Type: application/json

{
  "id": null,
  "title": "Ледниковый период",
  "description": "Доисторические животные объединяются, чтобы спасти человеческого детеныша. Смешно, душевно и очень красиво",
  "type": "Полнометражный",
  "genre": "Мультфильм",
  "date": "2002-03-12"
}

###Добавить несколько фильмов
POST http://localhost:8190/movie-api/addMovies
Content-Type: application/json

[
  {
    "id": null,
    "title": "Женщина в золотом",
    "description": "История Марии Альтманн, которая пытается добиться справедливости – вернуть ценности, отобранные у её семьи нацистами несколько десятилетий назад.",
    "type": "Полнометражный",
    "genre": "Драма",
    "date": "2015-02-15"
  },
  {
    "id": null,
    "title": "Очень странные дела",
    "description": "1980-е годы, тихий провинциальный американский городок. Благоприятное течение местной жизни нарушает загадочное исчезновение подростка по имени Уилл.",
    "type": "Сериал",
    "genre": "Фантастика",
    "date": "2016-07-11"
  },
  {
    "id": null,
    "title": "ДМБ ",
    "description": "Студент Штык соблазнил профессорскую жену, рабочий парень Бомба сжёг родной завод, завсегдатай казино Пуля скрывается от кредиторов. У всех одна дорога — на призывной пункт.",
    "type": "Полнометражный",
    "genre": "Комедия",
    "date": "2000-03-31"
  }

]


###Получить все фильмы
GET http://localhost:8190/movie-api/all


###Поиск фильма по дате выхода
GET http://localhost:8190/movie-api/byDate?date=1997-01-01



###Поиск фильма по названию
GET http://localhost:8190/movie-api/byTitle?title=Побег из Шоушенка



###Поиск фильма по типу
GET http://localhost:8190/movie-api/byType?type=Сериал



###Проверка обработки кастомной ошибки
GET http://localhost:8190/exception/myException


###Получить все фильмы
GET http://localhost:8190/movie-api/pagination?page=0&size=5


